network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      addresses:
        - 192.168.1.204/24
      gateway4: 192.168.1.1
      dhcp4: yes
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
    enp0s9:
      addresses:
        - 10.8.0.11/24
    enp0s10:
      addresses:
        - 10.9.0.11/24